Add Dhali-app
Dhali-org/Dhali-app pull request #1
Opened 2023-03-14 19:07 UTC by desimmons

This PR adds Dhali-app as a single commit

2023-03-14 21:02 UTC, robbie-daniels reviewed
* Shall we remove the "Help" tab for now?  It's just a placeholder at the moment and I think it's misleading:
![image](https://user-images.githubusercontent.com/70610994/225131872-8eb4b8e0-5c30-4603-9572-1c89c5ce0243.png)

* Love the test CI!
* Shall we also clean up all of the test apps?
* Do we want to have publishing to a staging area (rather than just the temporary links we get in PRs) for merge into `develop`, and prod in `main`?  This seems desirable, since I think we want to test things outside of PRs too.

2023-03-14 21:04 UTC, desimmons commented on README.md
> +
I'm not sure this is true

2023-03-14 21:10 UTC, desimmons commented on firestore.indexes.json
> +  // ]
Yup. Deleted

2023-03-14 21:13 UTC, desimmons commented on lib/wallet/balance_chart.dart
> +import 'package:flutter/material.dart';
Removed

2023-03-15 08:08 UTC, robbie-daniels commented on README.md
> +
Whoops you’re correct! I was mostly just thinking front the angle of: it seems unclear how people can use the client once they have it running

2023-03-15 16:41 UTC, robbie-daniels requested changes
* I believe we need to include copyright and license notices for our dependencies (I think most are MIT/BSD-3/ISC)

2023-03-15 20:16 UTC, desimmons commented
> * I believe we need to include copyright and license notices for our dependencies (I think most are MIT/BSD-3/ISC)

I've pushed an update to include a `LicensePage` widget in the Drawer

2023-03-16 10:41 UTC, robbie-daniels approved these changes

2023-03-16 11:28 UTC, robbie-daniels approved these changes

2023-03-16 11:29 UTC, merged